# Frontend workflow
name: Frontend Deploy
on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: sed "s|{{API_BASE}}|${{ secrets.API_URL }}|g" frontend/index.template.html > frontend/index.html
      - run: aws s3 sync frontend/ s3://amit-c00l-resume-website-cloudresumechallenge-click --delete
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
